apiVersion: v1
kind: Pod
metadata:
  name: dns-proxy
spec:
  containers:
  - name: proxy-tcp
    image: k8s.gcr.io/proxy-to-service:v2
    args: [ "tcp", "80", "kumogninx" ]
    ports:
    - name: tcp
      protocol: TCP
      containerPort: 80
      hostPort: 80
