# This will setup the git bits.
#
mod 'acme/ohmyzsh', '0.1.2'
mod 'nanliu/staging', '1.0.3'

# Repo bits
vcsrepo { '/Users/scoday/zProjects/scoday/DevOps/tbauto':
  ensure   => mirror,
  provider => git,
  source   => 'git://github.com:scoday/DevOps.git',
}
