---
- hosts: base
  become: root

  tasks:

  - name: ensure qemu1 is running
    service:
      name: machine-qemu\x2d1\x2dhndvsuse02.scope
      state: started
    become: true

  - name: install packages
    zypper: name={{ item }} update_cache=yes state=installed
    with_items:
        - git
        - ntp
        - bind-utils

  - name: resolv-config
    template: src=dns/resolv.conf dest=/etc/resolv.conf
    #notify:
    #  - restart $something # here for reference
